name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.2", "3.3", "3.4"]
        bundler: [default]
        gemfile:
          - rails-7.1
          - rails-7.2
          - rails-8.0
        include:
          - { ruby: "2.5", gemfile: "rails-5.2", bundler: "default" }
          - { ruby: "2.6", gemfile: "rails-5.2", bundler: "default" }
          - { ruby: "2.7", gemfile: "rails-6.0", bundler: "default" }
          - { ruby: "3.0", gemfile: "rails-6.1", bundler: "default" }
          - { ruby: "3.1", gemfile: "rails-7.0", bundler: "default" }

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true # runs `bundle install` and caches gems automatically
      - name: Run tests
        run: bundle exec rake
